// TuGraph embedded typed-neighbor driver for SemL0 3+3 baseline.
//
// Dense edge-list text format:
//   <vertex_count>
//   <src_dense> <edge_type> <dst_dense>
//
// The driver imports every dense edge type as a distinct outgoing TuGraph edge
// label (E_Px / E_Nx), then checks fixed-seed query truth TSV generated by
// dense_truth_driver.cpp.

#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <map>
#include <sstream>
#include <string>
#include <unordered_map>
#include <vector>

#include "lgraph/lgraph.h"

using clk = std::chrono::steady_clock;
using namespace lgraph_api;

static constexpr uint64_t MASK = ~0ULL;

struct Digest {
    uint64_t count = 0;
    uint64_t sum_hash = 0;
    uint64_t xor_hash = 0;
};

struct Query {
    size_t index = 0;
    int edge_type = 0;
    int64_t src = 0;
    Digest truth;
};

static uint64_t mix64(uint64_t x) {
    x += 0x9e3779b97f4a7c15ULL;
    x = (x ^ (x >> 30)) * 0xbf58476d1ce4e5b9ULL;
    x = (x ^ (x >> 27)) * 0x94d049bb133111ebULL;
    return x ^ (x >> 31);
}

static void digest_add(Digest& digest, uint64_t dst) {
    uint64_t h1 = mix64(dst);
    uint64_t h2 = mix64(dst ^ 0xd6e8feb86659fd93ULL);
    digest.count++;
    digest.sum_hash = (digest.sum_hash + h1) & MASK;
    digest.xor_hash ^= h2;
}

static std::string edge_label(int et) {
    if (et > 0) return "E_P" + std::to_string(et);
    return "E_N" + std::to_string(-et);
}

static long peak_rss_kb() {
    std::ifstream st("/proc/self/status");
    std::string line;
    while (std::getline(st, line)) {
        if (line.rfind("VmHWM:", 0) == 0) {
            long kb = 0;
            std::sscanf(line.c_str(), "VmHWM: %ld", &kb);
            return kb;
        }
    }
    return -1;
}

static std::vector<Query> read_truth(const std::string& path) {
    std::ifstream in(path);
    if (!in) throw std::runtime_error("cannot open truth tsv: " + path);
    std::string line;
    std::getline(in, line);
    std::vector<Query> out;
    while (std::getline(in, line)) {
        if (line.empty()) continue;
        std::stringstream ss(line);
        std::string tok;
        Query q;
        std::getline(ss, tok, '\t');
        q.index = std::stoull(tok);
        std::getline(ss, tok, '\t');
        q.edge_type = std::stoi(tok);
        std::getline(ss, tok, '\t');
        q.src = std::stoll(tok);
        std::getline(ss, tok, '\t');
        q.truth.count = std::stoull(tok);
        std::getline(ss, tok, '\t');
        q.truth.sum_hash = std::stoull(tok);
        std::getline(ss, tok, '\t');
        q.truth.xor_hash = std::stoull(tok);
        out.push_back(q);
    }
    return out;
}

static void write_json_escape(std::ostream& out, const std::string& s) {
    for (char c : s) {
        if (c == '"' || c == '\\') out << '\\' << c;
        else if (c == '\n') out << "\\n";
        else out << c;
    }
}

static void usage(const char* argv0) {
    std::cerr << "usage: " << argv0
              << " --edges <dense.txt> --truth <truth.tsv> --db-dir <dir> --output <json>"
              << " [--batch N] [--max-vertices N] [--max-edges N] [--skip-load]\n";
}

int main(int argc, char** argv) {
    std::string edges_path;
    std::string truth_path;
    std::string db_dir;
    std::string out_path = "-";
    uint64_t batch = 100000;
    uint64_t max_vertices = 0;
    uint64_t max_edges = 0;
    bool skip_load = false;

    for (int i = 1; i < argc; i++) {
        std::string arg = argv[i];
        auto next = [&]() -> std::string {
            if (++i >= argc) {
                std::cerr << "missing value after " << arg << "\n";
                std::exit(2);
            }
            return std::string(argv[i]);
        };
        if (arg == "--edges") edges_path = next();
        else if (arg == "--truth") truth_path = next();
        else if (arg == "--db-dir") db_dir = next();
        else if (arg == "--output") out_path = next();
        else if (arg == "--batch") batch = std::stoull(next());
        else if (arg == "--max-vertices") max_vertices = std::stoull(next());
        else if (arg == "--max-edges") max_edges = std::stoull(next());
        else if (arg == "--skip-load") skip_load = true;
        else {
            std::cerr << "unknown arg " << arg << "\n";
            usage(argv[0]);
            return 2;
        }
    }
    if (edges_path.empty() || truth_path.empty() || db_dir.empty()) {
        usage(argv[0]);
        return 2;
    }

    uint64_t vertex_count = 0;
    uint64_t loaded_vertices = 0;
    uint64_t loaded_edges = 0;
    double load_s = 0.0;
    double query_s = 0.0;
    uint64_t checked = 0;
    uint64_t mismatches = 0;
    uint64_t total_neighbors = 0;
    std::vector<std::string> mismatch_json;
    std::map<int, uint64_t> edge_type_counts;

    try {
        auto all_start = clk::now();
        Galaxy galaxy(db_dir, false, true);
        galaxy.SetCurrentUser("admin", "73@TuGraph");
        galaxy.CreateGraph("default", "SemL0 typed-neighbor baseline");
        GraphDB db = galaxy.OpenGraph("default", false);

        if (!skip_load) {
            auto load_start = clk::now();
            db.DropAllData();
            db.AddVertexLabel("V", {FieldSpec("id", FieldType::INT64, false)}, VertexOptions("id"));
            EdgeConstraints vv_constraints{{"V", "V"}};
            for (int et = -17; et <= 17; et++) {
                if (et == 0) continue;
                db.AddEdgeLabel(edge_label(et), {}, EdgeOptions(vv_constraints));
            }

            std::ifstream in(edges_path);
            if (!in) throw std::runtime_error("cannot open edges: " + edges_path);
            in >> vertex_count;
            uint64_t vertex_limit = max_vertices ? std::min(max_vertices, vertex_count) : vertex_count;
            {
                auto txn = db.CreateWriteTxn(false);
                size_t label_id = txn.GetVertexLabelId("V");
                std::vector<size_t> field_ids = txn.GetVertexFieldIds(label_id, {"id"});
                for (uint64_t vid = 0; vid < vertex_limit; vid++) {
                    txn.AddVertex(label_id, field_ids, {FieldData::Int64((int64_t)vid)});
                    loaded_vertices++;
                    if (loaded_vertices % batch == 0) {
                        txn.Commit();
                        txn = db.CreateWriteTxn(false);
                        label_id = txn.GetVertexLabelId("V");
                        field_ids = txn.GetVertexFieldIds(label_id, {"id"});
                    }
                }
                txn.Commit();
            }

            std::map<int, size_t> label_ids;
            {
                auto txn = db.CreateReadTxn();
                for (int et = -17; et <= 17; et++) {
                    if (et == 0) continue;
                    label_ids[et] = txn.GetEdgeLabelId(edge_label(et));
                }
                txn.Abort();
            }

            uint64_t src = 0, dst = 0;
            long et_long = 0;
            auto txn = db.CreateWriteTxn(false);
            while (in >> src >> et_long >> dst) {
                int et = (int)et_long;
                if (src >= vertex_limit || dst >= vertex_limit) continue;
                txn.AddEdge((int64_t)src, (int64_t)dst, label_ids[et], {}, {});
                loaded_edges++;
                edge_type_counts[et]++;
                if (max_edges && loaded_edges >= max_edges) break;
                if (loaded_edges % batch == 0) {
                    txn.Commit();
                    txn = db.CreateWriteTxn(false);
                }
            }
            txn.Commit();
            db.Flush();
            load_s = std::chrono::duration<double>(clk::now() - load_start).count();
        }

        auto queries = read_truth(truth_path);
        std::map<int, int16_t> query_label_ids;
        auto query_start = clk::now();
        auto txn = db.CreateReadTxn();
        for (int et = -17; et <= 17; et++) {
            if (et == 0) continue;
            query_label_ids[et] = (int16_t)txn.GetEdgeLabelId(edge_label(et));
        }
        std::vector<double> latencies_us;
        for (const auto& q : queries) {
            if (max_vertices && (uint64_t)q.src >= max_vertices) continue;
            auto t0 = clk::now();
            Digest got;
            auto vit = txn.GetVertexIterator(q.src, false);
            if (vit.IsValid()) {
                auto eit = vit.GetOutEdgeIterator();
                int16_t want = query_label_ids[q.edge_type];
                while (eit.IsValid()) {
                    if (eit.GetLabelId() == want) {
                        digest_add(got, (uint64_t)eit.GetDst());
                    }
                    eit.Next();
                }
            }
            double us = std::chrono::duration<double, std::micro>(clk::now() - t0).count();
            latencies_us.push_back(us);
            checked++;
            total_neighbors += got.count;
            if (got.count != q.truth.count || got.sum_hash != q.truth.sum_hash || got.xor_hash != q.truth.xor_hash) {
                mismatches++;
                if (mismatch_json.size() < 20) {
                    std::ostringstream m;
                    m << "{\"query_index\":" << q.index
                      << ",\"edge_type\":" << q.edge_type
                      << ",\"src\":" << q.src
                      << ",\"expected\":{\"count\":" << q.truth.count
                      << ",\"sum_hash\":" << q.truth.sum_hash
                      << ",\"xor_hash\":" << q.truth.xor_hash
                      << "},\"observed\":{\"count\":" << got.count
                      << ",\"sum_hash\":" << got.sum_hash
                      << ",\"xor_hash\":" << got.xor_hash << "}}";
                    mismatch_json.push_back(m.str());
                }
            }
        }
        txn.Abort();
        query_s = std::chrono::duration<double>(clk::now() - query_start).count();

        auto pct = [&](double p) -> double {
            if (latencies_us.empty()) return 0.0;
            auto vals = latencies_us;
            std::sort(vals.begin(), vals.end());
            size_t idx = (size_t)std::ceil((p / 100.0) * vals.size());
            if (idx == 0) idx = 1;
            idx = std::min(idx - 1, vals.size() - 1);
            return vals[idx];
        };
        double avg_us = 0.0;
        for (double v : latencies_us) avg_us += v;
        if (!latencies_us.empty()) avg_us /= (double)latencies_us.size();
        double total_s = std::chrono::duration<double>(clk::now() - all_start).count();

        std::ostream* outp = &std::cout;
        std::ofstream file_out;
        if (out_path != "-") {
            file_out.open(out_path);
            if (!file_out) throw std::runtime_error("cannot write output: " + out_path);
            outp = &file_out;
        }
        auto& out = *outp;
        out << "{\n";
        out << "  \"system\": \"TuGraph embedded\",\n";
        out << "  \"status\": \"" << (mismatches == 0 ? "PASS" : "FAIL") << "\",\n";
        out << "  \"db_dir\": \"";
        write_json_escape(out, db_dir);
        out << "\",\n";
        out << "  \"loaded_vertices\": " << loaded_vertices << ",\n";
        out << "  \"loaded_edges\": " << loaded_edges << ",\n";
        out << "  \"load_s\": " << load_s << ",\n";
        out << "  \"query_s\": " << query_s << ",\n";
        out << "  \"checked\": " << checked << ",\n";
        out << "  \"mismatches\": " << mismatches << ",\n";
        out << "  \"total_neighbors\": " << total_neighbors << ",\n";
        out << "  \"avg_us\": " << avg_us << ",\n";
        out << "  \"p50_us\": " << pct(50) << ",\n";
        out << "  \"p90_us\": " << pct(90) << ",\n";
        out << "  \"p99_us\": " << pct(99) << ",\n";
        out << "  \"peak_rss_kb\": " << peak_rss_kb() << ",\n";
        out << "  \"sample_mismatches\": [";
        for (size_t i = 0; i < mismatch_json.size(); i++) {
            if (i) out << ", ";
            out << mismatch_json[i];
        }
        out << "]\n";
        out << "}\n";
        return mismatches == 0 ? 0 : 1;
    } catch (const std::exception& e) {
        std::ofstream out(out_path == "-" ? "/dev/stdout" : out_path);
        out << "{\n  \"system\": \"TuGraph embedded\",\n  \"status\": \"ERROR\",\n  \"error\": \"";
        write_json_escape(out, e.what());
        out << "\",\n  \"loaded_vertices\": " << loaded_vertices
            << ",\n  \"loaded_edges\": " << loaded_edges << "\n}\n";
        std::cerr << "ERROR: " << e.what() << "\n";
        return 1;
    }
}
