#!/usr/bin/env python3
"""Render W10 SIGMOD-oriented TeX tables from frozen regenerated reports.

The input reports are themselves regenerated from raw W6/W7/W8/W9 JSON, TSV, and
JSONL artifacts by the matching summarizers. This renderer keeps the paper source
from hand-copying table numbers while preserving the W10 claim boundaries.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def strip_cell(cell: str) -> str:
    cell = cell.strip()
    if cell.startswith("`") and cell.endswith("`"):
        cell = cell[1:-1]
    return cell


def md_table_after(text: str, heading: str) -> list[dict[str, str]]:
    lines = text.splitlines()
    start = None
    for idx, line in enumerate(lines):
        if line.strip() == heading:
            start = idx + 1
            break
    if start is None:
        raise SystemExit(f"missing heading: {heading}")
    while start < len(lines) and not lines[start].lstrip().startswith("|"):
        start += 1
    if start + 1 >= len(lines):
        raise SystemExit(f"missing table after heading: {heading}")
    header = [strip_cell(c) for c in lines[start].strip().strip("|").split("|")]
    rows: list[dict[str, str]] = []
    idx = start + 2
    while idx < len(lines) and lines[idx].lstrip().startswith("|"):
        cells = [strip_cell(c) for c in lines[idx].strip().strip("|").split("|")]
        if len(cells) == len(header):
            rows.append(dict(zip(header, cells)))
        idx += 1
    return rows


def tex_escape(text: str) -> str:
    repl = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(repl.get(ch, ch) for ch in str(text))


def short_metric(text: str) -> str:
    first = str(text).split("+/-")[0].strip()
    return tex_escape(first)


def write_file(path: Path, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body.rstrip() + "\n", encoding="utf-8")


def table_env(label: str, caption: str, tabular: str, size: str = r"\small") -> str:
    return "\n".join(
        [
            "% Auto-generated by baseline/render_w10_sigmod_tables_20260615.py.",
            r"\begin{table}[t]",
            r"\centering",
            size,
            rf"\caption{{{caption}}}",
            rf"\label{{{label}}}",
            tabular,
            r"\end{table}",
            "",
        ]
    )


def render_evidence_overview(out_dir: Path) -> None:
    rows = [
        ("W6", "SF100 matrix", "measured", "Gate 1 FALLBACK; Gate 2 GO"),
        ("W7", "workload shift", "real-SF30-derived", "Gate=GO; not production trace"),
        ("W8", "property and 2-hop", "measured SF30", "2-hop candidate count mixed"),
        ("W9", "mixed read/write", "measured SF30", "steady-state coverage"),
        ("W13", "schema evolution", "measured tests", "10/10 pass; bounded scope"),
    ]
    body = [
        r"\begin{tabular}{llll}",
        r"\toprule",
        r"Block & Purpose & Evidence & Paper boundary \\",
        r"\midrule",
    ]
    for row in rows:
        body.append(" & ".join(tex_escape(c) for c in row) + r" \\")
    body.extend([r"\bottomrule", r"\end{tabular}"])
    write_file(
        out_dir / "w10-evidence-overview.tex",
        table_env("tab:w10-evidence-overview", "Frozen W10 evidence blocks.", "\n".join(body)),
    )


def render_w6(w6: str, out_dir: Path) -> None:
    rows = md_table_after(w6, "## Aggregate Matrix")
    body = [
        r"\begin{tabular}{lrrrrrl}",
        r"\toprule",
        r"Variant & Store GiB & L0 files & Ops & Candidate L0 & Read bytes & Avg us \\",
        r"\midrule",
    ]
    for row in rows:
        body.append(
            " & ".join(
                [
                    r"\texttt{" + tex_escape(row["variant"]) + "}",
                    tex_escape(row["store GiB"]),
                    tex_escape(row["L0 files"]),
                    tex_escape(row["ops/repeat"]),
                    short_metric(row["candidate L0 mean+/-std"]),
                    short_metric(row["read bytes mean+/-std"]),
                    short_metric(row["avg us mean+/-std"]),
                ]
            )
            + r" \\"
        )
    body.extend([r"\bottomrule", r"\end{tabular}"])
    write_file(
        out_dir / "w10-sf100-matrix.tex",
        table_env(
            "tab:w10-sf100-matrix",
            "W6 SF100 matrix regenerated from raw runner artifacts.",
            "\n".join(body),
            r"\scriptsize",
        ),
    )

    rss_rows = {row["variant"]: row["max RSS GiB"] for row in md_table_after(w6, "## Import RSS")}
    body = [
        r"\begin{tabular}{lp{0.18\linewidth}p{0.62\linewidth}}",
        r"\toprule",
        r"Gate & Decision & Paper use \\",
        r"\midrule",
        r"Latency & FALLBACK & \texttt{budg-b64} mean is lower than schema, but 1-stddev intervals overlap; no stable latency-superiority claim. \\",
        rf"RSS & GO & measured RSS: schema/naive={float(rss_rows['schema']) / float(rss_rows['naive']):.2f}x and \texttt{{budg-b64}}/naive={float(rss_rows['budg-b64']) / float(rss_rows['naive']):.2f}x. \\",
        r"\bottomrule",
        r"\end{tabular}",
    ]
    write_file(
        out_dir / "w10-gate-summary.tex",
        table_env("tab:w10-gates", "W6 Gate 1/2 interpretation.", "\n".join(body)),
    )


def render_w7(w7: str, out_dir: Path) -> None:
    rows = md_table_after(w7, "## Migration Summary")
    body = [
        r"\begin{tabular}{lrrrl}",
        r"\toprule",
        r"Variant & A hot flush & B hot flush & Changed & Paper boundary \\",
        r"\midrule",
    ]
    for row in rows:
        boundary = "self-tuning evidence" if row["variant"] == "feedback-only" else "control"
        body.append(
            " & ".join(
                [
                    r"\texttt{" + tex_escape(row["variant"]) + "}",
                    tex_escape(row["phase A hot-compaction flush"]),
                    tex_escape(row["phase B hot-compaction flush"]),
                    tex_escape(row["selected ranges changed"]),
                    tex_escape(boundary),
                ]
            )
            + r" \\"
        )
    body.extend([r"\bottomrule", r"\end{tabular}"])
    write_file(
        out_dir / "w10-w7-workload-shift.tex",
        table_env(
            "tab:w10-w7",
            "W7 workload-shift migration summary; input is real-SF30-derived.",
            "\n".join(body),
        ),
    )

    costs = [r for r in md_table_after(w7, "## Rewrite Cost") if r["variant"] == "feedback-only"]
    body = [
        r"\begin{tabular}{lrrrr}",
        r"\toprule",
        r"Phase & Hot compactions & Input & Output & Write amplification \\",
        r"\midrule",
    ]
    for row in costs:
        body.append(
            " & ".join(
                [
                    tex_escape(row["phase"]),
                    tex_escape(row["hot compactions"]),
                    tex_escape(row["compaction input"]),
                    tex_escape(row["compaction output"]),
                    tex_escape(row["write amplification"]),
                ]
            )
            + r" \\"
        )
    body.extend([r"\bottomrule", r"\end{tabular}"])
    write_file(
        out_dir / "w10-w7-rewrite-cost.tex",
        table_env("tab:w10-w7-cost", "W7 feedback rewrite-cost accounting.", "\n".join(body)),
    )


def render_w8(w8: str, out_dir: Path) -> None:
    prop = md_table_after(w8, "## Property deltas vs schema")
    hop = md_table_after(w8, "## 2-hop deltas vs schema")
    body = [
        r"\begin{tabular}{llrrrr}",
        r"\toprule",
        r"Workload & Variant & Candidate & Body reads & Read bytes & Elapsed \\",
        r"\midrule",
    ]
    for row in prop:
        body.append(
            " & ".join(
                [
                    "property",
                    r"\texttt{" + tex_escape(row["variant"]) + "}",
                    tex_escape(row["candidate L0 delta"]),
                    tex_escape(row["body reads delta"]),
                    tex_escape(row["read bytes delta"]),
                    tex_escape(row["elapsed delta"]),
                ]
            )
            + r" \\"
        )
    for row in hop:
        body.append(
            " & ".join(
                [
                    "2-hop",
                    r"\texttt{" + tex_escape(row["variant"]) + "}",
                    tex_escape(row["candidate L0 delta"]),
                    tex_escape(row["body reads delta"]),
                    tex_escape(row["read bytes delta"]),
                    tex_escape(row["elapsed delta"]),
                ]
            )
            + r" \\"
        )
    body.extend([r"\bottomrule", r"\end{tabular}"])
    write_file(
        out_dir / "w10-w8-property-2hop.tex",
        table_env("tab:w10-w8", "W8 property and 2-hop deltas versus schema.", "\n".join(body)),
    )


def render_w9(w9: str, out_dir: Path) -> None:
    agg = md_table_after(w9, "## Aggregate checkpoint summary")
    body = [
        r"\begin{tabular}{lrrrrrr}",
        r"\toprule",
        r"Variant & Queries & Candidate L0 & p50 us & p99 us & L0 files & Writer errors \\",
        r"\midrule",
    ]
    for row in agg:
        body.append(
            " & ".join(
                [
                    r"\texttt{" + tex_escape(row["variant"]) + "}",
                    tex_escape(row["total queries"]),
                    tex_escape(row["mean candidate L0"]),
                    tex_escape(row["mean p50 us"]),
                    tex_escape(row["mean p99 us"]),
                    tex_escape(row["last L0 files"]),
                    "0",
                ]
            )
            + r" \\"
        )
    body.extend([r"\bottomrule", r"\end{tabular}"])
    write_file(
        out_dir / "w10-w9-steady-state.tex",
        table_env("tab:w10-w9", "W9 SF30 mixed read/write steady-state summary.", "\n".join(body)),
    )

    delta = md_table_after(w9, "## Deltas vs schema")
    body = [
        r"\begin{tabular}{lrrrrr}",
        r"\toprule",
        r"Variant & Candidate L0 & p50 & p99 & L0 files & IO write bytes \\",
        r"\midrule",
    ]
    for row in delta:
        body.append(
            " & ".join(
                [
                    r"\texttt{" + tex_escape(row["variant"]) + "}",
                    tex_escape(row["mean candidate L0 delta"]),
                    tex_escape(row["mean p50 delta"]),
                    tex_escape(row["mean p99 delta"]),
                    tex_escape(row["last L0 files delta"]),
                    tex_escape(row["io write bytes delta"]),
                ]
            )
            + r" \\"
        )
    body.extend([r"\bottomrule", r"\end{tabular}"])
    write_file(
        out_dir / "w10-w9-deltas.tex",
        table_env("tab:w10-w9-deltas", "W9 deltas versus schema.", "\n".join(body)),
    )


def render_w13(w13: str, out_dir: Path) -> None:
    tests = [line for line in w13.splitlines() if "\tpass\t" in line]
    body = [
        r"\begin{tabular}{ll}",
        r"\toprule",
        r"Evidence & Paper boundary \\",
        r"\midrule",
        rf"Tests & {len(tests)}/10 pass \\",
        r"Schema epoch & Old segments remain readable under their stored epoch. \\",
        r"Pruning & Exact summaries may prune; mixed/unknown/tombstone-sensitive segments are conservative. \\",
        r"Out of scope & Full online migration, reclamation, and unrestricted type changes. \\",
        r"\bottomrule",
        r"\end{tabular}",
    ]
    write_file(
        out_dir / "w10-w13-schema-evolution.tex",
        table_env("tab:w10-w13", "W13 schema-evolution correctness boundary.", "\n".join(body)),
    )


def render_caveats(out_dir: Path) -> None:
    rows = [
        ("Gate 1", "No stable latency-superiority claim for budg-b64 over schema."),
        ("W7", "Real-SF30-derived workload-shift evidence, not full-store production trace."),
        ("W8", "2-hop improves body/read/elapsed but candidate L0 increases."),
        ("W9", "Semantic improves p50/p99 while increasing candidate L0 and L0 files."),
        ("W13", "Bounded additive/fixed-width/schema-epoch correctness only."),
        ("BACH", "Use as physical-locality motivation; Like.time range pruning is future work."),
    ]
    body = [r"\begin{tabular}{lp{0.72\linewidth}}", r"\toprule", r"Scope & Required wording \\", r"\midrule"]
    for row in rows:
        body.append(tex_escape(row[0]) + " & " + tex_escape(row[1]) + r" \\")
    body.extend([r"\bottomrule", r"\end{tabular}"])
    write_file(
        out_dir / "w10-caveats.tex",
        table_env("tab:w10-caveats", "Submission caveats that constrain final claims.", "\n".join(body)),
    )


def render_artifact_map(out_dir: Path) -> None:
    rows = [
        ("W6", "remote-logs/w6-sf100-matrix-20260613-132325", "baseline/sf100-matrix-20260613-cn.md"),
        ("W7", "remote-logs/w7-sf30-workload-shift-formal-20260615-1536", "baseline/w7-sf30-workload-shift-summary-20260615-cn.md"),
        ("W8", "remote-logs/w8-property-2hop-20260614-2025", "baseline/w8-property-2hop-summary-20260615-cn.md"),
        ("W9", "remote-logs/w9-steady-state-formal-20260615-1200", "baseline/w9-steady-state-summary-20260615-cn.md"),
        ("W13", "remote-logs/w13-schema-evolution-20260614-0004", "remote-logs/w13-schema-evolution-20260614-0004/summary.md"),
    ]
    body = [
        r"\begin{tabular}{lll}",
        r"\toprule",
        r"Block & Raw root & Regenerated report \\",
        r"\midrule",
    ]
    for row in rows:
        body.append(
            tex_escape(row[0]) + " & " + r"\path{" + row[1] + "}" + " & " + r"\path{" + row[2] + r"} \\"
        )
    body.extend([r"\bottomrule", r"\end{tabular}"])
    write_file(
        out_dir / "w10-artifact-map.tex",
        table_env("tab:w10-artifacts", "Artifact paths for frozen W10 evidence.", "\n".join(body), r"\scriptsize"),
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out-dir", default=ROOT / "paper" / "tables", type=Path)
    args = parser.parse_args()

    w6 = read(ROOT / "baseline" / "sf100-matrix-20260613-cn.md")
    w7 = read(ROOT / "baseline" / "w7-sf30-workload-shift-summary-20260615-cn.md")
    w8 = read(ROOT / "baseline" / "w8-property-2hop-summary-20260615-cn.md")
    w9 = read(ROOT / "baseline" / "w9-steady-state-summary-20260615-cn.md")
    w13 = read(ROOT / "baseline" / "w13-schema-evolution-summary-20260614.md")

    render_evidence_overview(args.out_dir)
    render_w6(w6, args.out_dir)
    render_w7(w7, args.out_dir)
    render_w8(w8, args.out_dir)
    render_w9(w9, args.out_dir)
    render_w13(w13, args.out_dir)
    render_caveats(args.out_dir)
    render_artifact_map(args.out_dir)


if __name__ == "__main__":
    main()
